nelmio_api_doc:
    documentation:
        info:
            title: Local Crew
            description: API for local crew
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1
